
name: dotnet-ci
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ./tests/SafeVault.Tests/SafeVault.Tests.csproj
      - name: Build
        run: dotnet build --no-restore ./tests/SafeVault.Tests/SafeVault.Tests.csproj
      - name: Test
        run: dotnet test --no-build ./tests/SafeVault.Tests/SafeVault.Tests.csproj -v minimal
